/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package restaurantapp;

import java.sql.*;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.proteanit.sql.DbUtils;


/**
 *
 * @author ayoub-hamza
 */
public class Articles_manquants extends javax.swing.JFrame {

    Connection conn=null;
    ResultSet rs=null;
    Statement st = null;
    PreparedStatement pst=null;
    PreparedStatement pst2=null ;
    
    public static String dateDuRepas ;
    public static String typeDuRepas ;
    
    int nbr_total_pr ;
    String id_me ;
    /**
     * Creates new form Articles_manquants
     */
    public Articles_manquants() {
        initComponents();
        conn=db.java_db();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2, size.height/2 - getHeight()/2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        submitCom = new javax.swing.JButton();
        laDate = new javax.swing.JTextField();
        leType = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Date repas  :");

        jLabel2.setText("Type repas :");

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table);

        submitCom.setText("Commander");
        submitCom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitComActionPerformed(evt);
            }
        });

        laDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laDateActionPerformed(evt);
            }
        });

        leType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leTypeActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel3.setText("Liste des articles manquantes");

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("Afficher");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(submitCom)
                .addGap(108, 108, 108))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(leType, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(laDate, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 180, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(88, 88, 88))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel3)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(laDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(leType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addComponent(submitCom)
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void laDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_laDateActionPerformed

    private void submitComActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitComActionPerformed
        // TODO add your handling code here:
       dateDuRepas = laDate.getText();
              typeDuRepas = leType.getText();
       Commande cm = new Commande();
       cm.setVisible(true);
       cm.setDateRepas(dateDuRepas);
       cm.setTypeRepas(typeDuRepas);
       this.dispose();
       
    }//GEN-LAST:event_submitComActionPerformed

    private void leTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leTypeActionPerformed
        // TODO add your handling code here:
       /*
        String da = laDate.getText();
       String ty = leType.getText();
        if((!" ".equals(ty))&(!" ".equals(da)))
        {
            try {            
               
               String sql ="select repas.id_menu,jour_menu , effectif_prevu_repas_etudiant , "
                       + "effectif_prevu_repas_maitre , effectif_prevu_repas_agent from repas join menu on "
                       + "repas.id_menu=menu.id_menu where date_repas = ? and type_repas_menu = ?";
               
               pst=conn.prepareStatement(sql);
               pst.setString(1,da);
               pst.setString(2,ty);
               rs = pst.executeQuery();
               while(rs.next()){
                   id_me = rs.getString(1);
                   String jr = rs.getString(2);
                   String ef_et = rs.getString(3);
                   String ef_mt = rs.getString(4);
                   String ef_ag = rs.getString(5);
                   
                   int nbr_pr_et = Integer.parseInt(ef_et);
                   int nbr_pr_mt = Integer.parseInt(ef_mt);
                   int nbr_pr_ag = Integer.parseInt(ef_ag);
                   
                   nbr_total_pr = nbr_pr_et + nbr_pr_mt + nbr_pr_ag ;
               }
           } catch (SQLException ex) {
               Logger.getLogger(FicheRepas.class.getName()).log(Level.SEVERE, null, ex);
           }         
 
           try {
                String _sql = "select nom_plat , designation_article , prix_hors_taxe_article ," +
                    "(( quantite_article_plat * 10 ) - quantite_stock_article) Quantite_necessaire FROM (" +
                    "(SELECT cmp.id_plat, nom_plat FROM plat p JOIN composition cmp ON p.id_plat = cmp.id_plat " +
                    "WHERE cmp.id_menu = 1 ) R INNER JOIN " +
                    "(SELECT designation_article , id_plat , prix_hors_taxe_article , quantite_stock_article ,"+
                    "quantite_article_plat FROM " +
                    "article art JOIN liste_articles_du_plat la ON art.id_article = la.id_article) k " +
                    "ON r.id_plat = k.id_plat) where quantite_stock_article < ( quantite_article_plat * 10 )"; 

                pst=conn.prepareStatement(_sql);
		String str ;
		str=String.valueOf(nbr_total_pr);
                pst.setString(1,str);
                pst.setString(2,id_me);
                pst.setString(3,str);
                rs = pst.executeQuery();
                table.setModel(DbUtils.resultSetToTableModel(rs));

           }
           catch (SQLException ex) {
               Logger.getLogger(FicheRepas.class.getName()).log(Level.SEVERE, null, ex);
           }            
           
           finally {
                try{
                    rs.close();
                    pst.close();
                }
                catch(Exception e){
            }
        }
        }
        */
    }//GEN-LAST:event_leTypeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String da = laDate.getText();
       String ty = leType.getText();
            try {            
               
               String sql ="select repas.id_menu, jour_menu , effectif_prevu_repas_etudiant , "
                       + "effectif_prevu_repas_maitre , effectif_prevu_repas_agent from repas join menu on "
                       + "repas.id_menu=menu.id_menu where date_repas = ? and type_repas_menu = ?";
               
               pst=conn.prepareStatement(sql);
               pst.setString(1,da);
               pst.setString(2,ty);
               rs = pst.executeQuery();
               while(rs.next()){
                   id_me = rs.getString(1);
                   String jr = rs.getString(2);
                   String ef_et = rs.getString(3);
                   String ef_mt = rs.getString(4);
                   String ef_ag = rs.getString(5);
                   
                   int nbr_pr_et = Integer.parseInt(ef_et);
                   int nbr_pr_mt = Integer.parseInt(ef_mt);
                   int nbr_pr_ag = Integer.parseInt(ef_ag);
                   
                   nbr_total_pr = nbr_pr_et + nbr_pr_mt + nbr_pr_ag ;
               }
           } catch (SQLException ex) {
               Logger.getLogger(FicheRepas.class.getName()).log(Level.SEVERE, null, ex);
           }         
 
           try {
                String _sql = "select nom_plat , designation_article , prix_hors_taxe_article ," +
                    "(( quantite_article_plat * ? ) - quantite_stock_article) Quantite_necessaire FROM (" +
                    "(SELECT cmp.id_plat, nom_plat FROM plat p JOIN composition cmp ON p.id_plat = cmp.id_plat " +
                    "WHERE cmp.id_menu = ? ) R INNER JOIN " +
                    "(SELECT designation_article , id_plat , prix_hors_taxe_article , quantite_stock_article ,"+
                    "quantite_article_plat FROM " +
                    "article art JOIN liste_articles_du_plat la ON art.id_article = la.id_article) k " +
                    "ON r.id_plat = k.id_plat) where quantite_stock_article < ( quantite_article_plat * ? )"; 

                pst=conn.prepareStatement(_sql);
		String str ;
		str=String.valueOf(nbr_total_pr);
                pst.setString(1,str);
                pst.setString(2,id_me);
                pst.setString(3,str);
                rs = pst.executeQuery();
                table.setModel(DbUtils.resultSetToTableModel(rs));

           }
           catch (SQLException ex) {
               Logger.getLogger(FicheRepas.class.getName()).log(Level.SEVERE, null, ex);
           }            
           
           finally {
                try{
                    rs.close();
                    pst.close();
                }
                catch(Exception e){
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Articles_manquants.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Articles_manquants.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Articles_manquants.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Articles_manquants.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Articles_manquants().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField laDate;
    private javax.swing.JTextField leType;
    private javax.swing.JButton submitCom;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables


    void setDateRepas(String da ) {
        //To change body of generated methods, choose Tools | Templates.
        laDate.setText(da);
        
    }

    void setTypeRepas(String ty ) {
         //To change body of generated methods, choose Tools | Templates.
        leType.setText(ty); 
    
    }

}
