/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package restaurantapp;

import java.sql.*;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import net.proteanit.sql.DbUtils;



/**
 *
 * @author ayoub-hamza
 */
public class Commande extends javax.swing.JFrame {
        
    Connection conn=null;
    ResultSet rs=null;
    Statement st = null;
    PreparedStatement pst=null;
    PreparedStatement pst2=null ;
    
    String id_me ;
    int nbr_total_pr ;
    
    /**
     * Creates new form Commande
     */
    public Commande() {
        initComponents();
        conn=db.java_db();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2, size.height/2 - getHeight()/2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        validation = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tt = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        daate = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        typ = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        validation.setText("Valider la commande ");
        validation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validationActionPerformed(evt);
            }
        });

        tt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tt);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel1.setText("La commande");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Liste d'articles à commander :");

        jLabel4.setText("Date :");

        daate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                daateActionPerformed(evt);
            }
        });

        jLabel5.setText("Type :");

        typ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typActionPerformed(evt);
            }
        });

        jButton1.setText("Afficher");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(171, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(293, 293, 293))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(139, 139, 139))))
            .addGroup(layout.createSequentialGroup()
                .addGap(203, 203, 203)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(278, 278, 278)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(daate, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(typ, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 468, Short.MAX_VALUE)
                        .addComponent(validation)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(daate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(typ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(validation)
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void validationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validationActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "succés");
    }//GEN-LAST:event_validationActionPerformed

    private void daateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_daateActionPerformed
        // TODO add your handling code here:
        /*
        String da = daate.getText();
        String ty = typ.getText();
            try {            
               
               String sql ="select repas.id_menu,jour_menu , effectif_prevu_repas_etudiant , "
                       + "effectif_prevu_repas_maitre , effectif_prevu_repas_agent from repas join "
                       + "menu on repas.id_menu=menu.id_menu where date_repas = ? and type_repas_menu = ?";
               pst=conn.prepareStatement(sql);
               pst.setString(1,da);
               pst.setString(2,ty);
               rs = pst.executeQuery();
               while(rs.next()){
                   id_me = rs.getString(1);
                   String jr = rs.getString(2);
                   String ef_et = rs.getString(3);
                   String ef_mt = rs.getString(4);
                   String ef_ag = rs.getString(5);
                   
                   int nbr_pr_et = Integer.parseInt(ef_et);
                   int nbr_pr_mt = Integer.parseInt(ef_mt);
                   int nbr_pr_ag = Integer.parseInt(ef_ag);
                   
                   nbr_total_pr = nbr_pr_et + nbr_pr_mt + nbr_pr_ag ;
               }
           } catch (SQLException ex) {
               Logger.getLogger(FicheRepas.class.getName()).log(Level.SEVERE, null, ex);
           }         
            try {
                String _sql = "select id_article , designation_article , prix_hors_taxe_article ,  "
                        + "(( quantite_article_plat * 10 )-quantite_stock_article ) Quantite_necessaire FROM"
                        + "((SELECT cmp.id_plat  FROM plat p JOIN composition cmp ON "
                        + "p.id_plat = cmp.id_plat WHERE cmp.id_menu = 1 ) R INNER JOIN (SELECT art.id_article , "
                        + "designation_article , id_plat , prix_hors_taxe_article , quantite_stock_article ,"
                        + "quantite_article_plat FROM article art JOIN liste_articles_du_plat la ON "
                        + "art.id_article = la.id_article) k ON r.id_plat = k.id_plat) where "
                        + "quantite_stock_article < ( quantite_article_plat * 10 ); " ;
                
                pst=conn.prepareStatement(_sql);
		String str ;
		str=String.valueOf(nbr_total_pr);
                pst.setString(1,str);
                pst.setString(2,id_me);
                pst.setString(3,str);
                rs = pst.executeQuery();
                tt.setModel(DbUtils.resultSetToTableModel(rs));

           }
           catch (SQLException ex) {
               Logger.getLogger(FicheRepas.class.getName()).log(Level.SEVERE, null, ex);
           }            
           
           finally {
                try{
                    rs.close();
                    pst.close();
                }
                catch(Exception e){
            }
        }
        */
    }//GEN-LAST:event_daateActionPerformed

    private void typActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_typActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String da = daate.getText();
        String ty = typ.getText();
            try {            
               
               String sql ="select repas.id_menu,jour_menu , effectif_prevu_repas_etudiant , "
                       + "effectif_prevu_repas_maitre , effectif_prevu_repas_agent from repas join "
                       + "menu on repas.id_menu=menu.id_menu where date_repas = ? and type_repas_menu = ?";
               pst=conn.prepareStatement(sql);
               pst.setString(1,da);
               pst.setString(2,ty);
               rs = pst.executeQuery();
               while(rs.next()){
                   id_me = rs.getString(1);
                   String jr = rs.getString(2);
                   String ef_et = rs.getString(3);
                   String ef_mt = rs.getString(4);
                   String ef_ag = rs.getString(5);
                   
                   int nbr_pr_et = Integer.parseInt(ef_et);
                   int nbr_pr_mt = Integer.parseInt(ef_mt);
                   int nbr_pr_ag = Integer.parseInt(ef_ag);
                   
                   nbr_total_pr = nbr_pr_et + nbr_pr_mt + nbr_pr_ag ;
               }
           } catch (SQLException ex) {
               Logger.getLogger(FicheRepas.class.getName()).log(Level.SEVERE, null, ex);
           }         
            try {
                String _sql = "select id_article , designation_article , prix_hors_taxe_article ,( quantite_article_plat * ? ) - quantite_stock_article FROM\n" +
                                "(\n" +
                                "(SELECT cmp.id_plat  FROM plat p JOIN\n" +
                                "composition cmp ON p.id_plat = cmp.id_plat WHERE cmp.id_menu = ? ) R\n" +
                                "\n" +
                                "INNER JOIN\n" +
                                "\n" +
                                "(SELECT art.id_article , designation_article , id_plat , prix_hors_taxe_article , quantite_stock_article \n" +
                                ",quantite_article_plat FROM article art JOIN liste_articles_du_plat la ON\n" +
                                "art.id_article = la.id_article) k\n" +
                                "\n" +
                                "ON r.id_plat = k.id_plat) where quantite_stock_article < ( quantite_article_plat * ? ) " ;
                
                pst=conn.prepareStatement(_sql);
		String str ;
		str=String.valueOf(nbr_total_pr);
                pst.setString(1,str);
                pst.setString(2,id_me);
                pst.setString(3,str);
                rs = pst.executeQuery();
                tt.setModel(DbUtils.resultSetToTableModel(rs));

           }
           catch (SQLException ex) {
               Logger.getLogger(FicheRepas.class.getName()).log(Level.SEVERE, null, ex);
           }            
           
           finally {
                try{
                    rs.close();
                    pst.close();
                }
                catch(Exception e){
            }
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Commande.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Commande.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Commande.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Commande.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Commande().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField daate;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tt;
    private javax.swing.JTextField typ;
    private javax.swing.JButton validation;
    // End of variables declaration//GEN-END:variables

    void setDateRepas(String da) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        daate.setText(da);
    }

    void setTypeRepas(String ty ) {
         //To change body of generated methods, choose Tools | Templates.
        typ.setText(ty); 
    
    }
}
