/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package restaurantapp;

import java.sql.*;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author ayoub-hamza
 */
public class FicheRepas extends javax.swing.JFrame {
    Connection conn=null;
    ResultSet rs=null;
    Statement st = null;
    PreparedStatement pst=null;
    PreparedStatement pst2=null ;
    String id_me ;
    int nbr_total_pr ;
    int id_repas = 0;

    /**
     * Creates new form FicheRepas
     */
    public FicheRepas() {
        initComponents();
        conn=db.java_db();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2, size.height/2 - getHeight()/2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        date_repas = new javax.swing.JTextField();
        type_rr = new javax.swing.JTextField();
        jour = new javax.swing.JTextField();
        et = new javax.swing.JTextField();
        mt = new javax.swing.JTextField();
        ag = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tab = new javax.swing.JTable();
        submit = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        nbr_impr = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Date repas :");

        jLabel2.setText("type repas :");

        jLabel3.setText("Le jour du repas :");

        jLabel4.setText("Effectif prévue :");

        jLabel5.setText("Etudiant :");

        jLabel6.setText("Maitres d'internat :");

        jLabel7.setText("Agents :");

        date_repas.setEditable(false);
        date_repas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                date_repasActionPerformed(evt);
            }
        });

        type_rr.setEditable(false);
        type_rr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                type_rrActionPerformed(evt);
            }
        });

        jour.setEditable(false);

        et.setEditable(false);

        mt.setEditable(false);
        mt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mtActionPerformed(evt);
            }
        });

        ag.setEditable(false);

        tab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tab);
        if (tab.getColumnModel().getColumnCount() > 0) {
            tab.getColumnModel().getColumn(0).setHeaderValue("Title 1");
            tab.getColumnModel().getColumn(1).setHeaderValue("Title 2");
            tab.getColumnModel().getColumn(2).setHeaderValue("Title 3");
            tab.getColumnModel().getColumn(3).setHeaderValue("Title 4");
        }

        submit.setText("Submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        jLabel9.setText("Effectif non prévue : ");

        jLabel10.setText("Liste des plats  :");

        jLabel11.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel11.setText("Fiche du repas");

        jButton1.setText("Afficher");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(259, 259, 259))
            .addGroup(layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(577, 577, 577)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(41, 41, 41)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(28, 28, 28))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(et)
                                    .addComponent(mt)
                                    .addComponent(ag)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(date_repas, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(type_rr, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jour, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(114, 114, 114)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48)))))
                .addGap(71, 71, 71))
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(nbr_impr, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(submit)
                .addGap(240, 240, 240))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(date_repas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(type_rr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(et, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(ag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(submit)
                    .addComponent(nbr_impr, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void date_repasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_date_repasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_date_repasActionPerformed

    private void type_rrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_type_rrActionPerformed
        // TODO add your handling code here:
       /*
        String da = date_repas.getText();
       String ty = type_rr.getText();
        if((!" ".equals(ty))&(!" ".equals(da)))
        {
           try {            
               
               String sql ="select repas.id_menu,jour_menu , effectif_prevu_repas_etudiant ,"
                       + "effectif_prevu_repas_maitre , effectif_prevu_repas_agent from repas "
                       + "join menu on repas.id_menu=menu.id_menu where date_repas = ? and type_repas_menu = ?";

               pst=conn.prepareStatement(sql);
               pst.setString(1,da);
               pst.setString(2,ty);
               rs = pst.executeQuery();
               while(rs.next()){
                   id_me = rs.getString(1);
                   String jr = rs.getString(2);
                   jour.setText(jr);
                   String ef_et = rs.getString(3);
                   et.setText(ef_et);
                   String ef_mt = rs.getString(4);
                   mt.setText(ef_mt);
                   String ef_ag = rs.getString(5);
                   ag.setText(ef_ag);
                   
                   int nbr_pr_et = Integer.parseInt(ef_et);
                   int nbr_pr_mt = Integer.parseInt(ef_mt);
                   int nbr_pr_ag = Integer.parseInt(ef_ag);
                   
                   nbr_total_pr = nbr_pr_et + nbr_pr_mt + nbr_pr_ag ;
               }
           } catch (SQLException ex) {
               Logger.getLogger(FicheRepas.class.getName()).log(Level.SEVERE, null, ex);
           }
           try {
                String _sql = "select nom_plat , designation_article , prix_hors_taxe_article , "
                        + "quantite_article_plat * ? FROM((SELECT cmp.id_plat, nom_plat FROM plat p "
                        + "JOIN composition cmp ON p.id_plat = cmp.id_plat WHERE cmp.id_menu = ? ) R "
                        + "INNER JOIN (SELECT designation_article , quantite_article_plat, la.id_plat , "
                        + "prix_hors_taxe_article  FROM article art JOIN liste_articles_du_plat la ON art.id_article = la.id_article) k "
                        + "ON r.id_plat = k.id_plat )" ;
                pst=conn.prepareStatement(_sql);
		String str ;
		str=String.valueOf(nbr_total_pr);
                pst.setString(1,str);
                pst.setString(2,id_me);
                rs = pst.executeQuery();
                tab.setModel(DbUtils.resultSetToTableModel(rs));
           }
           catch (SQLException ex) {
               Logger.getLogger(FicheRepas.class.getName()).log(Level.SEVERE, null, ex);
           }            
           
           finally {
                try{
                    rs.close();
                    pst.close();
                }
                catch(Exception e){
            }
        }
        }
        */
    }//GEN-LAST:event_type_rrActionPerformed

    private void mtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mtActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        try {
            // TODO add your handling code here:
            String nbr_non = nbr_impr.getText();
            String dd = date_repas.getText();
            String typer = type_rr.getText();
            String sql_re = "SELECT * FROM repas where id_repas = ? ";
            pst=conn.prepareStatement(sql_re);
            pst.setInt(1,id_repas);
            rs = pst.executeQuery();
            int count = 0;
            while( rs.next() ){
                count++;
            }
            if( count == 0 ){
                String sql_re2 = "insert into repas(effectif_imprevu_repas) values( ? ) where id_repas = ? ";
                pst = conn.prepareStatement(sql_re2);
                pst.setInt(1,Integer.parseInt(nbr_non));
                pst.setInt(2,id_repas);
                rs = pst.executeQuery();
            }else{
                String sql_re13 = "UPDATE repas set effectif_imprevu_repas = ? where id_repas = ? ";
                pst = conn.prepareStatement(sql_re13);
                pst.setInt(1,Integer.parseInt(nbr_non));
                pst.setInt(2,id_repas);
                rs = pst.executeQuery();
            }
            JOptionPane.showMessageDialog(null, "succes");
        } catch (SQLException ex) {
            Logger.getLogger(FicheRepas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_submitActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String da = date_repas.getText();
       String ty = type_rr.getText();   
            try {            
               
               String sql ="select repas.id_menu,jour_menu , effectif_prevu_repas_etudiant ,"
                       + "effectif_prevu_repas_maitre , effectif_prevu_repas_agent , id_repas from repas "
                       + "join menu on repas.id_menu=menu.id_menu where date_repas = ? and type_repas_menu = ?";
               pst=conn.prepareStatement(sql);
               pst.setString(1,da);
               pst.setString(2,ty);
               rs = pst.executeQuery();
               while(rs.next()){
                   id_me = rs.getString(1);
                   String jr = rs.getString(2);
                   jour.setText(jr);
                   String ef_et = rs.getString(3);
                   et.setText(ef_et);
                   String ef_mt = rs.getString(4);
                   mt.setText(ef_mt);
                   String ef_ag = rs.getString(5);
                   ag.setText(ef_ag);
                   id_repas = rs.getInt(6);
                   int nbr_pr_et = Integer.parseInt(ef_et);
                   int nbr_pr_mt = Integer.parseInt(ef_mt);
                   int nbr_pr_ag = Integer.parseInt(ef_ag);
                   
                   nbr_total_pr = nbr_pr_et + nbr_pr_mt + nbr_pr_ag ;
               }
           } catch (SQLException ex) {
               Logger.getLogger(FicheRepas.class.getName()).log(Level.SEVERE, null, ex);
           }
           try {
                String _sql = "select nom_plat , designation_article , prix_hors_taxe_article , "
                        + "quantite_article_plat * ? FROM((SELECT cmp.id_plat, nom_plat FROM plat p "
                        + "JOIN composition cmp ON p.id_plat = cmp.id_plat WHERE cmp.id_menu = ? ) R "
                        + "INNER JOIN (SELECT designation_article , quantite_article_plat, la.id_plat , "
                        + "prix_hors_taxe_article  FROM article art JOIN liste_articles_du_plat la ON art.id_article = la.id_article) k "
                        + "ON r.id_plat = k.id_plat )" ;
                pst=conn.prepareStatement(_sql);
		String str ;
		str=String.valueOf(nbr_total_pr);
                pst.setString(1,str);
                pst.setString(2,id_me);
                rs = pst.executeQuery();
                tab.setModel(DbUtils.resultSetToTableModel(rs));
           }
           catch (SQLException ex) {
               Logger.getLogger(FicheRepas.class.getName()).log(Level.SEVERE, null, ex);
           }            
           
           finally {
                try{
                    rs.close();
                    pst.close();
                }
                catch(Exception e){
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FicheRepas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FicheRepas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FicheRepas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FicheRepas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
            
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FicheRepas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ag;
    private javax.swing.JTextField date_repas;
    private javax.swing.JTextField et;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jour;
    private javax.swing.JTextField mt;
    private javax.swing.JTextField nbr_impr;
    private javax.swing.JButton submit;
    private javax.swing.JTable tab;
    private javax.swing.JTextField type_rr;
    // End of variables declaration//GEN-END:variables

    void setDateRepas(String da ) {
        //To change body of generated methods, choose Tools | Templates.
        date_repas.setText(da);
        
    }

    void setTypeRepas(String ty ) {
         //To change body of generated methods, choose Tools | Templates.
        type_rr.setText(ty); 
    
    }
}
