/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package restaurantapp;

import java.sql.*;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author ayoub-hamza
 */
public class NvRepas extends javax.swing.JFrame {
    Connection conn=null;
    ResultSet rs=null;
    Statement st = null;
    PreparedStatement pst=null;
    PreparedStatement pst2=null;
    String type_repas ;
    String nhar ;
    int id_menu = 0 ;
    
    /**
     * Creates new form NvRepas
     */
    public NvRepas() {
        initComponents();
        conn=db.java_db();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2, 
        size.height/2 - getHeight()/2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MyGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        type_1 = new javax.swing.JRadioButton();
        type_2 = new javax.swing.JRadioButton();
        type_3 = new javax.swing.JRadioButton();
        Nbr_etudiants = new javax.swing.JTextField();
        Nbr_maitres = new javax.swing.JTextField();
        Nbr_agents = new javax.swing.JTextField();
        date = new javax.swing.JTextField();
        submit = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        day = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setText("Date du repat :");

        jLabel2.setText("Type du repas :");

        jLabel3.setText("Effectif prévue :");

        jLabel4.setText("Petit déjeuner");

        jLabel5.setText("Déjeuner");

        jLabel6.setText("Dinner");

        jLabel7.setText("étudiants :");

        jLabel8.setText("maîtres d’internat :");

        jLabel9.setText("agents domestiques :");

        MyGroup.add(type_1);
        type_1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        type_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                type_1MouseClicked(evt);
            }
        });
        type_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                type_1ActionPerformed(evt);
            }
        });

        MyGroup.add(type_2);
        type_2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        type_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                type_2MouseClicked(evt);
            }
        });
        type_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                type_2ActionPerformed(evt);
            }
        });

        MyGroup.add(type_3);
        type_3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        type_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                type_3MouseClicked(evt);
            }
        });
        type_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                type_3ActionPerformed(evt);
            }
        });

        Nbr_etudiants.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nbr_etudiantsActionPerformed(evt);
            }
        });

        Nbr_maitres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nbr_maitresActionPerformed(evt);
            }
        });

        Nbr_agents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nbr_agentsActionPerformed(evt);
            }
        });

        date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateActionPerformed(evt);
            }
        });

        submit.setText("submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        jLabel10.setText("jour :");

        day.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dayActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel11.setText("Insérer le nouveau repas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(submit)
                .addGap(88, 88, 88))
            .addGroup(layout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(234, 234, 234)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(day, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(type_1)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel4))
                                    .addComponent(date, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(type_2)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(type_3)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(39, 39, 39)
                                    .addComponent(Nbr_etudiants, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Nbr_agents, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Nbr_maitres, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(227, 259, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel11)
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(day, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(type_1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addComponent(type_2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(type_3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(23, 23, 23)
                .addComponent(jLabel3)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(Nbr_etudiants, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nbr_maitres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(Nbr_agents, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(submit)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Nbr_maitresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nbr_maitresActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_Nbr_maitresActionPerformed

    private void Nbr_etudiantsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nbr_etudiantsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Nbr_etudiantsActionPerformed

    private void dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        // TODO add your handling code here:
        try{
            System.out.println(type_repas);
            String theDay = day.getText();
            String sql = "select id_menu from menu where jour_menu = ? and type_repas_menu = ? ";
            pst=conn.prepareStatement(sql);
            pst.setString(1,theDay);
            pst.setString(2,type_repas);
            rs = pst.executeQuery();
            while(rs.next()){
                //nhar = rs.getString(1);
                id_menu=rs.getInt("id_menu");
            }
            System.out.println(id_menu);
            String sql3 = " select * FROM repas where date_repas = ? AND id_menu = ? " ; 
            pst = conn.prepareStatement(sql3);
            pst.setString(1,date.getText());
            pst.setInt(2,id_menu);
            rs = pst.executeQuery();
            //Inserer d , nbr_et , nbr_mait , nbr_ag et type_repas
            int countt=0;
            while(rs.next()){
                countt++;
            }
            if(countt == 0){
                String _sql = "insert into repas(date_repas , effectif_prevu_repas_etudiant ,"
                        + " effectif_prevu_repas_maitre ,effectif_prevu_repas_agent ,"
                        + " id_menu) values (? , ? , ? , ? , ?)";
                String d = date.getText();
                String nbr_et = Nbr_etudiants.getText();
                String nbr_mait = Nbr_maitres.getText();
                String nbr_ag = Nbr_agents.getText();
                pst=conn.prepareStatement(_sql);
                pst.setString(1,d);
                pst.setInt(2,Integer.parseInt(nbr_et));
                pst.setInt(3,Integer.parseInt(nbr_mait));
                pst.setInt(4,Integer.parseInt(nbr_ag));
                pst.setInt(5,id_menu);
                rs = pst.executeQuery();
            }
            else{
                String _sql = "UPDATE repas set effectif_prevu_repas_etudiant = ? ,"
                        + " effectif_prevu_repas_maitre = ? ,effectif_prevu_repas_agent = ? "
                        + " WHERE id_menu = ? AND date_repas = ? ";
                String d = date.getText();
                String nbr_et = Nbr_etudiants.getText();
                String nbr_mait = Nbr_maitres.getText();
                String nbr_ag = Nbr_agents.getText();
                pst=conn.prepareStatement(_sql);
                pst.setString(5,d);
                pst.setInt(2,Integer.parseInt(nbr_et));
                pst.setInt(3,Integer.parseInt(nbr_mait));
                pst.setInt(4,Integer.parseInt(nbr_ag));
                pst.setInt(4,id_menu);
                rs = pst.executeQuery();
            }
        }catch(Exception e){
            e.printStackTrace();
        }
        finally {
            try{
                rs.close();
                pst.close();
                JOptionPane.showMessageDialog(null, "succes");
            }
            catch(Exception e){
            }
        }
        
    }//GEN-LAST:event_submitActionPerformed

    private void Nbr_agentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nbr_agentsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Nbr_agentsActionPerformed

    private void type_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_type_1ActionPerformed
        // TODO add your handling code here:
        type_repas = "petit_dejeuner";
    }//GEN-LAST:event_type_1ActionPerformed

    private void type_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_type_2ActionPerformed
        // TODO add your handling code here:
        type_repas = "dejeuner";
    }//GEN-LAST:event_type_2ActionPerformed

    private void type_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_type_3ActionPerformed
        // TODO add your handling code here:
        type_repas = "diner";
    }//GEN-LAST:event_type_3ActionPerformed

    private void dayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dayActionPerformed

    private void type_1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_type_1MouseClicked
        // TODO add your handling code here:
        type_repas = "petit_dejeuner";
    }//GEN-LAST:event_type_1MouseClicked

    private void type_2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_type_2MouseClicked
        // TODO add your handling code here:
        type_repas = "dejeuner";
    }//GEN-LAST:event_type_2MouseClicked

    private void type_3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_type_3MouseClicked
        // TODO add your handling code here:
        type_repas = "diner";
    }//GEN-LAST:event_type_3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NvRepas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NvRepas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NvRepas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NvRepas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NvRepas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup MyGroup;
    private javax.swing.JTextField Nbr_agents;
    private javax.swing.JTextField Nbr_etudiants;
    private javax.swing.JTextField Nbr_maitres;
    private javax.swing.JTextField date;
    private javax.swing.JTextField day;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton submit;
    private javax.swing.JRadioButton type_1;
    private javax.swing.JRadioButton type_2;
    private javax.swing.JRadioButton type_3;
    // End of variables declaration//GEN-END:variables
}
